---
version: '2'

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest-dev
    container_name: zigbee2mqtt
    network_mode: host
    restart: always
    group_add:
      - dialout
      - uucp
    ports:
      - "8888:8080"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ~/data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/Berlin


  #--- docker run -d --name homeassistant --privileged --restart=always -e TZ=Europe/Berlin -v /home/$USER/homeassistant:/config -v /home/$USER/homeassistant/ssh:/tts --network=host  ghcr.io/home-assistant/home-assistant:stable
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    restart: always
    volumes:
      - ~/homeassistant:/config
      - ~/homeassistant/tts:/tts:ro
      - ~/homeassistant/media:/media:rw
    environment:
      - TZ=Europe/Berlin
    privileged: true

